// Menu
export const SWITCH_MENU = 'SWITCH_MENU';

//Auth
export const CREATE_CLIENT = "CREATE_CLIENT";
export const CREATE_CLIENT_FULFILLED = "CREATE_CLIENT_FULFILLED";
export const CREATE_CLIENT_REJECTED = "CREATE_CLIENT_REJECTED";
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";
export const REQUEST_TOKEN = "REQUEST_TOKEN";
export const REQUEST_TOKEN_FULFILLED = "REQUEST_TOKEN_FULFILLED";
export const REQUEST_TOKEN_REJECTED = "REQUEST_TOKEN_REJECTED";