// Menu
export const SWITCH_MENU = 'SWITCH_MENU';

//Auth
export const CREATE_CLIENT = "CREATE_CLIENT";
export const CREATE_CLIENT_FULFILLED = "CREATE_CLIENT_FULFILLED";
export const CREATE_CLIENT_REJECTED = "CREATE_CLIENT_REJECTED";
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_FULFILLED = "CREATE_USER_FULFILLED";
export const CREATE_USER_REJECTED = "CREATE_USER_REJECTED";
export const REQUEST_TOKEN = "REQUEST_TOKEN";
export const REQUEST_TOKEN_FULFILLED = "REQUEST_TOKEN_FULFILLED";
export const REQUEST_TOKEN_REJECTED = "REQUEST_TOKEN_REJECTED";
export const CLEAR_AUTH_RESPONSES = "CLEAR_AUTH_RESPONSES";
//

//Database
export const CREATE_DATABASE = "CREATE_DATABASE";
export const CREATE_DATABASE_FULFILLED = "CREATE_DATABASE_FULFILLED";
export const CREATE_DATABASE_REJECTED = "CREATE_DATABASE_REJECTED";
export const DELETE_DATABASE = "DELETE_DATABASE";
export const DELETE_DATABASE_FULFILLED = "DELETE_DATABASE_FULFILLED";
export const DELETE_DATABASE_REJECTED = "DELETE_DATABASE_REJECTED";
export const CLEAR_DATABASE_RESPONSES = "CLEAR_DATABASE_RESPONSES";
//