// Menu
export const SWITCH_MENU = 'SWITCH_MENU';

//Auth
export const CREATE_CLIENT = "CREATE_CLIENT";
export const CREATE_CLIENT_FULFILLED = "CREATE_CLIENT_FULFILLED";
export const CREATE_CLIENT_REJECTED = "CREATE_CLIENT_REJECTED";